language: python
python:
  - "3.6"

sudo: false
  
script:
    - sphinx-build -b html doc/source doc/build
    
deploy:
  - provider: pages:git
    verbose: true
    token: $GITHUB_TOKEN
    edge: true
    local_dir: ./doc/build/
    keep_history: false
    skip_cleanup: true
